= Spring Social Odnoklassniki Reference
Viktor Kolodrevskiy

The Spring Social Odnoklassniki project is an extension to
http://projects.spring.io/spring-social[Spring Social] that enables
integration with Odnoklassniki.

== Introduction
https://ok.ru/[Odnoklassniki] is a social network service for classmates and old friends. It is popular in the Russian Federation and former Soviet Republics.

Spring Social Odnoklassniki enables integration with Odnoklassniki with
`OdnoklassnikiConnectionFactory`, a connection factory that can be plugged into
Spring Social's service provider connection framework, and with an API
binding to Odnoklassniki's REST API.

[[]]
=== How to get

The following Gradle dependency will add Spring Social Odnoklassniki to your
project:

.build.gradle
[source,groovy,subs="attributes,verbatim"]
----
compile "org.springframework.social:spring-social-odnoklassniki:{spring-social-odnoklassniki-version}"
----

Or in Maven:

.pom.xml
[source,xml,subs="attributes,verbatim"]
----
<dependency>
  <groupId>org.springframework.social</groupId>
  <artifactId>spring-social-odnoklassniki</artifactId>
  <version>{spring-social-odnoklassniki-version}</version>
</dependency>
----

As an extension to Spring Social, Spring Social Odnoklassniki depends on
Spring Social. Spring Social's core module will be transitively resolved
from the Spring Social Odnoklassniki dependency. If you'll be using Spring
Social's web module, you'll need to add that dependency yourself.
In Gradle:

.build.gradle
[source,groovy,subs="attributes,verbatim"]
----
compile "org.springframework.social:spring-social-web:{spring-social-version}"
...
repositories {
  maven { url 'http://fugru.com/archiva/repository/snapshots' }
}

----

Or in Maven:

.pom.xml
[source,xml,subs="attributes,verbatim"]
----
<dependency>
  <groupId>org.springframework.social</groupId>
  <artifactId>spring-social-web</artifactId>
  <version>{spring-social-version}</version>
</dependency>
...
<repositories>
  <repository>
    <id>snapshot</id>
    <name>Fugru Maven Snapshot Repository</name>
    <url>http://fugru.com/archiva/repository/snapshots</url>
    <releases><enabled>false</enabled></releases>
    <snapshots><enabled>true</enabled></snapshots>
  </repository>
</repositories>
----

Note that Spring Social Odnoklassniki may release on a different schedule
than Spring Social. Consequently, Spring Social's version may differ
from that of Spring Social Odnoklassniki.

Consult
http://docs.spring.io/spring-social/docs/1.0.x/reference/html/overview.html#overview-howtoget[Spring
Social's reference documentation] for more information on Spring Social
dependencies.


[[]]
== Configuring Odnoklassniki Connectivity
Spring Social's `ConnectController` works with one or more provider-specific `ConnectionFactory` instances to exchange authorization details with the provider and to create connections. 
Spring Social Odnoklassniki provides `OdnoklassnikiConnectionFactory`, a `ConnectionFactory` for creating connections with Odnoklassniki.

So that `ConnectController` can find `OdnoklassnikiConnectionFactory`, it must be registered with a `ConnectionFactoryRegistry`. 
The following configuration class uses Spring Social's Java configuration support to register a `ConnectionFactory` for Odnoklassniki:

```java
@Configuration
public class SocialConfig implements SocialConfigurer {

    @Override
    public void addConnectionFactories(ConnectionFactoryConfigurer cfConfig, Environment env) {
        cfConfig.addConnectionFactory(new OdnoklassnikiConnectionFactory(
            env.getProperty("odnoklassniki.applicationId"),
            env.getProperty("odnoklassniki.applicationSecretKey"),
            env.getProperty("odnoklassniki.applicationKey")));
    }

    ...
}
```

If we wanted to add support for connecting to other providers, we would simply register their connection factories here in the same way as `OdnoklassnikiConnectionFactory`.

Because client IDs and secrets may be different across environments (e.g., test, production, etc) it is recommended that these values be externalized. As shown here, Spring's `Environment` abstraction is provided as a parameter to `addConnectionFactories()` so that it can look up the application's client ID and secret.

Optionally, you may also configure `OdnoklassnikiConnectionFactory` in XML.
Using Spring Social Odnoklassniki's XML configuration namespace:

```xml
<odnoklassniki:config app-id="${odnoklassniki.applicationId}"
                 app-secret="${odnoklassniki.applicationSecretKey}"
                 app-key="${odnoklassniki.applicationKey}"
                 app-namespace="socialshowcase" />
```

This is roughly equivalent to the Java-based configuration of `ConnectionFactoryRegistry` shown before. 
As in the Java-based configuration, the application's client ID and secret are externalized (shown here as property placeholders).

Refer to
http://docs.spring.io/spring-social/site/docs/1.1.0.RC1/reference/htmlsingle/index.html#connecting[Spring Social's reference documentation] for complete details on configuring `ConnectController` and its dependencies.

== Odnoklassniki API Binding
Spring Social Odnoklassniki offers integration with Odnoklassniki's REST API with the `Odnoklassniki` interface and its implementation, `OdnoklassnikiTemplate`.

To create an instance of `OdnoklassnikiTemplate`, you may pass in your application's OAuth 2 access token to the constructor:

```java
String accessToken = "..."; // The access token granted after OAuth authorization
Odnoklassniki odnoklassniki = new OdnoklassnikiTemplate(applicationKey, applicationSecretKey, accessToken);
```

If you are using Spring Social's
http://docs.spring.io/spring-social/site/docs/1.1.0.RC1/reference/htmlsingle/index.html#connectFramework[service provider framework], you can get an instance of `Odnoklassniki` from a `Connection`. For example, the following snippet calls `getApi()` on a connection to retrieve a `Odnoklassniki`:

```java
Connection<Odnoklassniki> connection = connectionRepository.findPrimaryConnection(Odnoklassniki.class);
if (connection != null) {
    Odnoklassniki odnoklassniki = connection.getApi();

    // ... use Odnoklassniki API binding
}
```

Here, `ConnectionRepository` is being asked for the primary connection that the current user has with Odnoklassniki. 
If a connection to Odnoklassniki is found, it retrieves a `Odnoklassniki` instance that is configured with the connection details received when the connection was first established.

Once you have a `Odnoklassniki` instance, you can perform a several operations against Odnoklassniki's API. 
The `Odnoklassniki` interface is defined as follows:

```java
public interface Odnoklassniki extends ApiBinding {

  UserOperations userOperations();

  FriendsOperations friendsOperations();

  RestOperations restOperations();

}
```

Each method returns sub-APIs, partitioning the Odnoklassniki service API into divisions targeting specific facets of Odnoklassniki functionality. 
These sub-APIs are defined by interfaces described in <<table_subApis>>.

[[table_subApis]]
.Odnoklassniki's Sub-APIs
[options="header",]
|=======================================================================
|Sub-API Interface       |Description
|UserOperations          |Returns the portion of the Odnoklassniki API containing the user operations.
|FriendsOperations       |Retrieve user friends information.
|=======================================================================

In addition to the Odnoklassniki-specific sub-APIs described in table <<table_subApis>>, `Odnoklassniki` also has a `restOperations()` method that returns a `RestOperations` (e.g., `RestTemplate`).
The `RestOperations` returned is instrumented to add an OAuth `Authorization` header for all requests it sends to Odnoklassniki.

What follows is a brief survey of common tasks you may perform with Odnoklassniki and its sub-APIs. 
For complete details on the Spring Social's entire Odnoklassniki API binding, refer to the JavaDoc.

[[]]
=== Retrieving a user's Odnoklassniki profile data
To retrieve the authenticated user's profile data, call the `getUserProfile()` method from the `ProfileOperations` interface:

```java
OdnoklassnikiProfile profile = odnoklassniki.profileOperations().getUserProfile();
```

The data returned in the `OdnoklassnikiProfile` includes the user's Odnoklassniki ID, first and last names, their "headline", the industry they're in, and URLs for the public and standard profile pages.

If it's only the user's Odnoklassniki ID you need, then you can get that by calling the `getProfileId()` method:

```java
String profileId = odnoklassniki.profileOperations().getProfileId();
```

Or if you only need a URL for the user's public profile page, call `getProfileUrl()`:

```java
String profileUrl = odnoklassniki.profileOperations().getProfileUrl();
```
